# -*- coding: utf-8 -*-
"""python-dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hf6Sj_4SuJ0QQQYxNkWileO2Sd2cSK9c
"""

def decimal_to_binary(start, end):
  binary_dict = {}
  for i in range(start, end + 1):
    temp = i
    string1 = ""
    if i == 0:
      binary_dict[i] = "0000"
      continue
    while temp > 0:
      remainder = temp % 2
      string1 += str(remainder)
      temp //= 2
    binary_dict[i] = string1[::-1].rjust(4, '0')
  return binary_dict

print(decimal_to_binary(0, 15))