# -*- coding: utf-8 -*-
"""python-dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hf6Sj_4SuJ0QQQYxNkWileO2Sd2cSK9c
"""

def decimal_to_binary(start, end):
  binary_dict = {}
  for i in range(start, end + 1):
    binary_num = bin(i)[2:].zfill(4)  # Convert to binary, remove "0b" prefix, pad with zeros
    binary_dict[i] = binary_num
  return binary_dict

decimal_to_binary(0, 15)