# -*- coding: utf-8 -*-
"""is-anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2u49hi3cHOTtUxHOT013SaUY7SBd_k3
"""

def is_anagram(str1,str2):
 list1 = []
 list2 = []

 for i in range(len(str1)):
  list1.append(str1[i])

 for i in range(len(str2)):
  list2.append(str2[i])

  list1.sort()
  list2.sort()

  if list1 == list2:
    return True
  else:
    return False

is_anagram('cat','rat')
is_anagram('cautioned','education')