# -*- coding: utf-8 -*-
"""reading-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhaK2gOZmNq83HQlLTkMqeRrKJDinKL7

#mtcars.csv file
"""

import pandas as pd

df = pd.read_csv('mtcars.csv')
df

df.to_csv('N_mtcars.csv', index=False) # Save with a different name

df1 = pd.read_csv('N_mtcars.csv')
df1

#Compare
comparison_result = df.equals(df1)
comparison_result

"""#beer.txt file"""

df2 = pd.read_csv('beer.txt', sep =' ')
df2

df2.to_csv('N_beer.txt',sep =' ', index=False)

df3 = pd.read_csv('N_beer.txt', sep =' ')
df3

comparison_result = df2.equals(df3)
comparison_result

"""#NHL 2015-16.xlsx file"""

df4 = pd.read_excel('NHL 2015-16.xlsx')
df4

df4.to_excel('N_NHL 2015-16.xlsx', index=False)

df5 = pd.read_excel('N_NHL 2015-16.xlsx')
df5

"""#U.data file"""

df6 = pd.read_csv('u.data', sep='\t', header = None)
df6

df6.to_csv('N_u.data', sep='\t', index=False)

df7 = pd.read_csv('N_u.data', sep='\t', header = None)
df7

comparison_result = df6.equals(df7)
comparison_result

"""#u.item file"""

df8 = pd.read_csv('u.item', sep ='|', encoding='latin-1', header = None)
df8

df8.to_csv('N_u.items', sep ='|', index=False)

df9 = pd.read_csv('N_u.items', sep ='|', header = None)
df9

comparison_result = df8.equals(df9)
comparison_result

"""#Function

- Without using try, except
"""

def read_files(fileName):
        if fileName.endswith('.csv'):
            df = pd.read_csv(fileName)
        elif fileName.endswith('.xlsx'):
            df = pd.read_excel(fileName)
        elif fileName.endswith('.txt'):
            df = pd.read_csv(fileName, sep=' ')
        elif fileName.endswith('.data'):
            df = pd.read_csv(fileName, sep='\t', header= None)
        elif fileName.endswith('.item'):
            df = pd.read_csv(fileName, sep='|', encoding='latin-1', header= None)
        else:
            print('Unsupported file format')
            return None
        return df

read_files('u.data')

"""- using try, except"""

def read_all_files(fileName):
    try:
        if fileName.endswith('.csv'):
            df = pd.read_csv(fileName)
        elif fileName.endswith('.xlsx'):
            df = pd.read_excel(fileName)
        elif fileName.endswith('.txt'):
            df = pd.read_csv(fileName, sep=' ')
        elif fileName.endswith('.data'):
            df = pd.read_csv(fileName, sep='\t', header= None)
        elif fileName.endswith('.item'):
            df = pd.read_csv(fileName, sep='|', encoding='latin-1', header= None)
        else:
            print('Unsupported file format')
            return None
        return df
    except FileNotFoundError:
        print(f"Error: File '{fileName}' not found.")
        return None

read_all_files('mtcars.txxt')

read_all_files('car.csv')

read_all_files('mtcars.csv')

read_all_files('beer.txt')

read_all_files('N_NHL 2015-16.xlsx')

read_all_files('u.data')

read_all_files('u.item')