# -*- coding: utf-8 -*-
"""reading-json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G19zXULxNW205jmb9sxecA6CvssOW7E5
"""

import json

with open("json_file.txt", "r") as f:
  json_f = json.load(f)

json_f

for i in json_f:
  for key, value in i.items():
    print(f'{key} : {value}')
  print("=================")

with open("daily_covid_cases.json", "r") as f:
  covid_json_f = json.load(f)

for key, value in covid_json_f.items():
    print(f"{key}")
    for x, y in value.items():
        print(f"{x}: {y}")
    print(" \n ")