# -*- coding: utf-8 -*-
"""telecom-db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAcYrET8Rz6ZGMgDp5TIlcbIZINoWQZl
"""

import pandas as pd
import sqlite3

"""# Retrieve table names from the database (telecom.db)"""

conn = sqlite3.connect("telecom.db")
conn

tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables

tables.fetchall()

"""# Join all tables in the database on the primary key."""

train = pd.read_sql("Select * FROM train",conn)
train

event_type = pd.read_sql("Select * FROM event_type",conn)
event_type

severity_type = pd.read_sql("Select * FROM severity_type",conn)
severity_type

resource_type = pd.read_sql("Select * FROM resource_type",conn)
resource_type

log_feature = pd.read_sql("Select * FROM log_feature",conn)
log_feature

train.to_sql('train_table', conn, if_exists='replace', index=False)
event_type.to_sql('event_type_table', conn, if_exists='replace', index=False)
severity_type.to_sql('severity_type_table', conn, if_exists='replace', index=False)
resource_type.to_sql('resource_type_table', conn, if_exists='replace', index=False)
log_feature.to_sql('log_feature_table', conn, if_exists='replace', index=False)


joined_df = pd.read_sql("""
    SELECT t.id, t.location, t.fault_severity, et.event_type, st.severity_type, rt.resource_type, lft.log_feature, lft.volume
    FROM train_table t
    INNER JOIN event_type_table et
    ON t.id = et.id
    INNER JOIN severity_type_table st
    ON t.id = st.id
    INNER JOIN resource_type_table rt
    ON t.id = rt.id
    INNER JOIN log_feature_table lft
    ON t.id = lft.id;
""", conn)

joined_df

joined_df.to_sql('joined_table', conn, if_exists='replace', index=False)

"""# Find unique occurrences of event_type and severity in the table from #2 using an SQL query.


"""

unique_event_severity = pd.read_sql("""
    SELECT Distinct event_type, severity_type
    FROM joined_table
""", conn)

unique_event_severity

"""# Find how many occurrences there are of each fault_severity in the table from #2 using an SQL query."""

fault_severity_count = pd.read_sql("""
    SELECT fault_severity, count (*) as occurances
    FROM joined_table
    Group By fault_severity
""", conn)

fault_severity_count