# -*- coding: utf-8 -*-
"""stroke-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiZIySOENcrwH5S9DzIJUOimSiALhshB
"""

import pandas as pd

stroke_df = pd.read_csv('healthcare-dataset-stroke-data.csv')
stroke_df

stroke_df.describe()

"""# Filter .describe() to only compute statistics on factors with floating point number values."""

stroke_df.describe(include = 'float') #I can use stroke.select_dtype(include = 'float)

"""# Use .groupby() to create a data frame grouping by the "stroke" factor."""

stroke = stroke_df.groupby("stroke")
stroke

"""# Use the "stroke" grouping to get only group where "stroke" is 1."""

stroke_1 = stroke.get_group(1)
stroke_1

"""# Use .describe() to compute statistics on factors with floating point values for the data where "stroke" is 1."""

stroke_1.describe(include = 'float')

"""# Filter .describe() to only compute statistics on factors with integer values, removing as much percentile data as possible."""

stroke_df.describe(include = 'int', percentiles = [])

"""# Create a data frame grouping by both the "hypertension" and "heart_disease" factors."""

factors_df = stroke_df.groupby(['hypertension', 'heart_disease'])
factors_df

"""# Get the group where both "hypertension" and "heart_disease" are 1."""

factors_df.get_group((1,1)) #get_group(tuple)

"""# Count the number of unique "id"s per group."""

factors_df['id'].nunique()

"""# Aggregate both the mean and standard deviation of "stroke" per group."""

factors_df['stroke'].agg(['mean', 'std'])