# -*- coding: utf-8 -*-
"""birthday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPVZUsf0KVd4PMdSOgS3HfgTKkIP1aPn
"""

import datetime as dt

def age_calc(date_birth): #The argument could be a string or datetime object
    try:
        date_today = dt.date.today()
        if isinstance(date_birth, str): #if string should transform it to datetime object with a specific format
          date_birth = dt.datetime.strptime(date_birth, "%m-%d-%Y").date()
        age = (date_today - date_birth).days // 365
        return age
    except:
        print(f"Invalid date format, Please provide date as mm-dd-yyyy)")

age_calc("19-01-1998") #dd-mm-yyyy

age_calc("01-19-1998")

age_calc("19/01/1998") #used / instead of -

age_calc(dt.date(1998, 1, 19)) #datetime object