# -*- coding: utf-8 -*-
"""thanksgiving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejfa7J-8uc37EVeyLWJleLpj8sVW7DGi
"""

import datetime as dt

date1 =dt.date.today()
date1

date2 = dt.date(2024, 11, 28)
date2

days_til_thanksgiving = (date2 - date1).days
days_til_thanksgiving