# -*- coding: utf-8 -*-
"""Python_Lists_Tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107i-ETY1EK6lHRmGAARkIb4OxeWvRiIY
"""

def alpha_index(alpha_list):
  d = {}
  for i in range(len(alpha_list)):
    d[alpha_list[i]] = i + 1
  return list(zip(d.values(),d.keys()))

L = 'abcdefghijklmnopqrstuvwxyz'
alpha_index(L)