# -*- coding: utf-8 -*-
"""visualization-project-laptop-sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xw77_e3Ne9LCt-82u4678e9QqQ8cS7R3
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

sales =pd.read_csv('Sales_data.txt')
sales

sales.info()

"""# What is target market? Male or female?

## OBSERVATION: Male is the target market resulting of a higher profit for the company and a higher confidence interval.
"""

sns.barplot(x='Contact Sex', y='Profit', data=sales, estimator = 'sum');
plt.title("Profit by Gender");

"""# If business is cash-constrained, which gender should be targeted?
## Hint: business being cash-constrained means cost to business should be considered (consider shipping cost)


### OBSERVATION: Total cost for Male is lower than Female so if business is cash-constrained, Male should be targeted costing the company less.
"""

sales['Total Cost'] = sales['Our Cost'] + sales['Shipping Cost']

cost_profit_by_gender = sales.groupby('Contact Sex').agg({'Total Cost': 'sum', 'Profit': 'sum'})

cost_profit_by_gender['Cost per Profit'] = cost_profit_by_gender['Total Cost'] / cost_profit_by_gender['Profit'] #Focus on cost efficiency.



sns.barplot(x=cost_profit_by_gender.index, y='Cost per Profit', data=cost_profit_by_gender);
plt.title("Cost per unit of profit by gender");
plt.xlabel("Gender");
plt.ylabel("Cost per unit of profit");

"""# If consumer is cash-constrained, which gender should be targeted?
## Hint: consumer being cash-constrained means cost to consumer should be considered

### Observation:  Males should be targeted having a sale price less than females, as when consumer is cash constrained they prioritize affordability having a limited budget.
"""

consumer_cost_by_gender = sales.groupby('Contact Sex')['Sale Price'].sum();


sns.barplot(x=consumer_cost_by_gender.index, y=consumer_cost_by_gender.values)
plt.title("Consumer Cost by Gender")
plt.xlabel("Gender")
plt.ylabel("Consumer Cost");

"""# What is our target age to maximize profit?
## Hint: consider individual ages and age ranges



### OBSERVATION: target age range is between 50 - 60 precisely 54
"""

sns.barplot(x= 'Contact Age', y= 'Profit',data = sales);
plt.title('Profit by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Profit');

sales['Age Group'] = pd.cut(sales['Contact Age'], bins=[20, 30, 40, 50,60] , labels=['20 - 30', '30 - 40', '40 - 50', '50 - 60'])

age_group_profit = sales.groupby('Age Group', observed = False)['Profit'].mean()


sns.barplot(x=age_group_profit.index, y=age_group_profit.values);
plt.title('Sum Profit by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Sum Profit');

"""#Which product should we feature?
## Hint: consider profit


### OBSERVATION:  Laptop because the company is getting the highest profit by selling it.
"""

sns.barplot(x='Product Type', y='Profit', data = sales, estimator = 'sum');
plt.title("Profit by Product Type");

"""# What lead sources have worked in the past: website, flyer, or email?
## Hint: consider profit

### OBSERVATION: Flyers
"""

sns.barplot(x='Lead Source', y='Profit', data = sales, estimator = 'sum');
plt.title("Profit by Lead Source");

sales['Lead Source'] = sales['Lead Source'].replace({'Flyer 1': 'Flyer', 'Flyer 2': 'Flyer', 'Flyer 3': 'Flyer', 'Flyer 4': 'Flyer'})

lead_source_profit = sales.groupby('Lead Source')['Profit'].mean()


sns.barplot(x=lead_source_profit.index, y=lead_source_profit.values, estimator = 'sum');
plt.title('Sum Profit by Lead Source');
plt.xlabel('Lead Source');
plt.ylabel('Sum Profit');

"""#When is the best time to do email marketing?

### OBSERVATION: November
"""

email = sales[sales['Lead Source'] == 'Email']
email

monthly_email = email['Sale Month'].value_counts()
monthly_email

sns.barplot(x = monthly_email.index, y = monthly_email.values, estimator = 'sum');
plt.title('Email Leads by Month');
plt.xlabel('Month');
plt.ylabel('Number of Leads');

