# -*- coding: utf-8 -*-
"""human-resources-db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15QtMgNVdZ-rx-1_Md_OYNzlIJFbI_3lZ
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect("hr.db")
conn

"""# Retrieve table names from the database (hr.db)."""

tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables

tables.fetchall()

"""# Retrieve EmployeeNumber, Department, Age, Gender, and Attrition for employees in sales department from the Employee table; save that information into a dataframe named ‘sales’."""

sales = pd.read_sql("SELECT EmployeeNumber, Department, Age, Gender, Attrition FROM employee WHERE Department = 'Sales'", conn)
sales

field = pd.read_sql("SELECT EmployeeNumber, EducationField, Age, Gender, Attrition FROM employee WHERE EducationField = 'Life Sciences'", conn)
field

sales.to_sql('sales_table', conn, if_exists='replace', index=False)
field.to_sql('field_table', conn, if_exists='replace', index=False)


joined_df = pd.read_sql("""
    SELECT *
    FROM sales_table st
    INNER JOIN field_table  ft
    ON st.EmployeeNumber = ft.EmployeeNumber;
""", conn)

joined_df