# -*- coding: utf-8 -*-
"""scraping-formula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ViRtvMSEMGt95gaR05NVvpaLhmkg3DJ7
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

"""# Connect to the web server and make sure you receive an ‘ok’ status code."""

url ="https://www.formula1.com/en/results/2022/drivers"
r = requests.get(url)

r.status_code

"""# Scrape the page for the statistics stored in the table."""

soup = BeautifulSoup(r.content)

tables = soup.find_all('table')[0]

header = tables.find_all('th')

headers = []
for h in header:
  headers.append(h.get_text())

row = tables.find_all('tr')

rows = []
for tr in row[1:]:
  tds = tr.find_all('td')
  row = [td.get_text() for td in tds]
  rows.append(row)

"""# Save the table as a data frame."""

df = pd.DataFrame(rows, columns = headers)
df

"""# Save the data frame as a .csv file, and re-read the file to make sure it saved correctly."""

df.to_csv('formula1.csv', index=False)

pd.read_csv('formula1.csv')

"""# Scrape the page using the pd.read_html( ) method."""

df_pd = pd.read_html(url)[0]
df_pd

