# -*- coding: utf-8 -*-
"""merge-join-telecom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bdr5Bf2hMH3ezhdsyx5d5v4x1m_f1QFe
"""

import pandas as pd

event_type = pd.read_csv("event_type.csv")
log_feature = pd.read_csv("log_feature.csv")
resource_type = pd.read_csv("resource_type.csv")
severity_type = pd.read_csv("severity_type.csv")
train = pd.read_csv("train.csv")

"""# Merging Tables"""

event_type

log_feature

resource_type

severity_type

train

dfs = [event_type, log_feature, resource_type, severity_type, train]
df = dfs[0]
for i in range(1, len(dfs)):
    df = pd.merge(df, dfs[i], on='id', how='outer') # Use 'outer' to keep all rows

df

"""# Explain the difference between inner and outer merge:

## Inner: is intersection, which means only the commun data between all dataframes.
## Outer: is union, which means adding all data existing in all dataframes regardless if it is commun or not.

# Explain the difference between merge and join:

## Merge: Allow merging on multiple columns
## Join: Single column merge.

# Divide dataset into two dataframes.
"""

df1 = df[:73211]
df2 = df[73211:]

df1

df2

"""# Concat the two dataframes."""

df_concat = pd.concat([df1, df2], axis = 0)
df_concat

df.equals(df_concat)

"""# Handle duplicates."""

df.info()

duplicates = df.duplicated()
duplicates

df_drop_dup = df.drop_duplicates()

df.duplicated().sum()

df.equals(df_drop_dup)

df

df_drop_dup

df_drop_dupID = df.drop_duplicates(subset = 'id')

df.equals(df_drop_dupID)

df_drop_dupID